# Module 4 - Popular Data Science Packages in Python

**_Author: Jessica Cervi_**

**Expected time = 1.5 hours**

**Total points = 90 points**


## Assignment Overview


In this assignment you will work with the material you learned in Module 4, packages scripts, such as the `Numpy` and `pandas` librariers. You will learn how to import packages and how to use their functions. You will also test your knowledge on 1D and 2D `NumPy` arrays. In the second half of the assignment, you will be asked to work with DataFrames.  You will be asked to create DataFrames and to select dataseries. Finally, you will be asked to filter the data in a DataFrame and compute basic statistic on its entries.


This assignment is designed to build your familiarity and comfort coding in Python while also helping you review key topics from each module. As you progress through the assignment, answers will get increasingly complex. It is important that you adopt a data scientist's mindset when completing this assignment. Remember to run your code from each cell before submitting your assignment. Running your code beforehand will notify you of errors and give you a chance to fix them before submitting. You should view your Vocareum submission as if you are delivering a final project to your manager or client.

**Vocareum Tips**

- Do not add arguments or options to functions unless you are specifically asked to. This will cause an error in Vocareum.
- Do not use a library unless you are expicitly asked to in the question.
- You can download the Grading Report after submitting the assignment. This will include feedback and hints on incorrect questions.


### Learning Objectives

 - Import and use packages in Jupyter Notebooks. 
 - Distinguish between NumPy arrays and lists. 
 - Use NumPy functions for basic statistical analyses. 
 - Practice filtering and slicing DataFrames with pandas. 




## Index:

#### Module 4: Popular Data Science Packages in Python

- [Question 1](#Question-1)
- [Question 2](#Question-2)
- [Question 3](#Question-3)
- [Question 4](#Question-4)
- [Question 5](#Question-5)
- [Question 6](#Question-6)
- [Question 7](#Question-7)
- [Question 8](#Question-8)
- [Question 9](#Question-9)
- [Question 10](#Question-10)
- [Question 11](#Question-11)
- [Question 12](#Question-12)
- [Question 13](#Question-13)
- [Question 14](#Question-14)
- [Question 15](#Question-15)
- [Question 16](#Question-16)



## Module 4: Popular Data Science Packages in Python


In this assignment, we will be testing your knowledge of the topics covered in Module 4, such as importing packages, Numpy arrays, pandas DataFrames. Finally, we will test your knowledge about subsetting anf filtering DataFrames and about applying Numpy statistical functions to a Dataframe.

### Importing packages and functions, aliasing
We will begin this assignment with a review of the `NumPy` and `pandas` libraries. As you have learned, `NumPy` is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices and `pandas` is a software library written for the Python programming language for data manipulation and analysis. We will start with some basic questions about aliasing a package and importing functions.

[Back to top](#Index:) 

### Question 1

5 points 

What is the correct syntax to use if you want to alias the library `Numpy` using `np` in your code? 
    - a) use numpy like np
    - b) import numpy as np
    - c) from numpy import np
    - d) use np like numpy

Assign the character  associated with your answer as a string to `ans1`. For, example if you believe `a` is the correct answer, submit yur answer as `ans1 = a`.

In [30]:
### YOUR SOLUTION HERE
ans1 = 'b'

###
### YOUR CODE HERE
###


NameError: name 'c' is not defined

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 2

5 points 

What is the correct syntax to use if you want to alias the library  `pandas` using `pd` in your code? 
    - a) import Pandas as pd 
    - b) use pandas a pd
    - c) import pandas as pd
    - d) from pandas use pd

Assign the character associated with your answer as a string to `ans2`. For, example if you believe `a` is the correct answer, submit yur answer as `ans2 = a`.

In [2]:
### YOUR SOLUTION HERE
ans2 = 'c'

###
### YOUR CODE HERE
###


NameError: name 'c' is not defined

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 3

5 points 

What is the correct syntax to use if you want to import just the function .square() from `NumPy`? 
    - a) from numpy import .square()
    - b) from numpy get square
    - c) use square from numpy
    - d) from numpy import square

Assign the character associated with your answer as a string to `ans3`.

In [3]:
### YOUR SOLUTION HERE
ans3 = 'd'

###
### YOUR CODE HERE
###


NameError: name 'b' is not defined

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### The NumPy library
NumPy is a Python package that stands for Numeric Python. The most useful tool in this package is a new data type called an array. Numpy also comes with sophisticated functions and linear algebra and random number capabilities.
In the next questions, we will learn how to create numpy arrays, how to perform basic operations on them, and how to slice them.

You can find more information about the `NumPy` package [here](https://numpy.org/doc/1.18/reference/index.html).


**Note: Questions 4, 5, 6, and 7 are connected and must to be answered in sequence.**

[Back to top](#Index:) 

### Question 4
5 points 

Given `distance=[2000,4000,6000,7000,1000]`, use `np.array()` to create a numpy array from `distance`. Name this array `np_distance`.

In [5]:
#impoting numpy and pandas
import numpy as np
import pandas as pd

In [7]:
distance=[2000,4000,6000,7000,1000]

### YOUR SOLUTION HERE
np_distance = np.array(distance)
np_distance
###
### YOUR CODE HERE
###


array([2000, 4000, 6000, 7000, 1000])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 5
5 points 

Divide `np_distance` by 1000 to obtain the distance in kilometers. Name this array `np_distance_km`.

In [8]:
### YOUR SOLUTION HERE
np_distance_km = np.array(np_distance/1000)
np_distance_km

###
### YOUR CODE HERE
###


array([2., 4., 6., 7., 1.])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 6
5 points 

Given time=[0.5, 1,1.3,1.5,2], use `np.array()` to create a numpy array from time. Name this array `np_time`. Next, divide `np_distance_km` by `np_time`. Name this array `np_velocity`.



In [9]:
time=[0.5, 1,1.3,1.5,2]

### YOUR SOLUTION HERE
np_time = np.array(time)
np_velocity = np.array(np_distance_km/np_time)
np_velocity

###
### YOUR CODE HERE
###


array([4.        , 4.        , 4.61538462, 4.66666667, 0.5       ])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 7
5 points 

Because we got some new new information about ora data, change the second last element of `np_velocity` to 1.8. Name this array `np_velocity_fixed`.


In [16]:
### YOUR SOLUTION HERE
np_velocity_fixed = np.array(np_velocity)
np_velocity_fixed[3] = 1.8
print(np_velocity_fixed)
###
### YOUR CODE HERE
###


[4.         4.         4.61538462 1.8        0.5       ]


In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Getting started with NumPy 2D arrays

In `NumPy`, rather than creating a numpy array with 1 dimension, you can create arrays that have more than one dimension. In the next questions you will work with 2D numpy arrays and retrieve the data you want from it.  


**Note: Questions 8, 9, 10, and 11 are connected and must be answered in sequence.**

[Back to top](#Index:) 

### Question 8
5 points 

`body_measurement`, defined below, contains 4 body measurements of four students. Each of these elements is a list containing the height and the weight of 4 students.
Given body_measurement defined below, use `np.array()` to create a 2D NumPy array from body_measurement. Name it `np_body_measurement`.


In [19]:
body_measurement = [[168, 55.4],
            [155, 47.7],
            [175, 69.5],
            [189, 90.2]]

### YOUR SOLUTION HERE
np_body_measurement= np.array(body_measurement)
###np_body_measurement.shape
np_body_measurement


###
### YOUR CODE HERE
###


array([[168. ,  55.4],
       [155. ,  47.7],
       [175. ,  69.5],
       [189. ,  90.2]])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 9
5 points 

Use the numpy function `shape` to get the shape of `np_body_measurement`. Assign the shape to the variable `ans9`.

In [22]:
### YOUR SOLUTION HERE
ans9= np_body_measurement.shape
ans9
###
### YOUR CODE HERE
###


(4, 2)

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 10
5 points 


Select the body measurments of the second student in np_body_measurement and assign it to `second_student`.


In [24]:
### YOUR SOLUTION HERE
second_student= np_body_measurement[1]
second_student

###
### YOUR CODE HERE
###


array([155. ,  47.7])

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 11
5 points 


Select the weight of the third student in np_body_measurement and assign it to `weight_third_student`.

In [25]:
### YOUR SOLUTION HERE
weight_third_student= np_body_measurement[2,1]
weight_third_student

###
### YOUR CODE HERE
###


69.5

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### Getting started with Pandas and Numpy statistical tools

`Pandas` is a very powerful Python library designed to analize and manipulate data. A very important data type that `pandas` allow to create are pandas DataFrame. A DataFrame is a data structure that allows you to store different data types in rows and columns. In the next questions, we will learn how to create, subset, and slice DataFrames. Finally, you will be asked to perform some basic statistic on pandas DataFrame using NumPy tools.

You can find more information about the `Pandas` package [here](https://pandas.pydata.org/pandas-docs/stable/getting_started/index.html#getting-started).

**Note: Questions 14,15 and 16 are connected and must be answered in sequence.**


[Back to top](#Index:) 

### Question 12
5 points 

Convert `museum`, given below, to a pandas DataFrame. Name the dataframe `df_museum`

In [27]:
museum = {
    'museum':['Louvre','Hermitage','National Gallery','Metropolitan'],
    'Picasso':[True,False,True,False]
}

### YOUR SOLUTION HERE
import pandas as pd
df_museum = pd.DataFrame(museum)
df_museum

###
### YOUR CODE HERE
###


museum  Picasso
0            Louvre     True
1         Hermitage    False
2  National Gallery     True
3      Metropolitan    False

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 13
5 points 

Assume that a database is saved as `students.csv`. What is the correct syntax to use in pandas to load the database into a pandas DataFrame called `df_students`?

    - a) df_students = pd.read_csv("students.csv")
    - b) df_students = pd.DataFrame("students.csv")
    - c) df_students = pd.csv_to_df("students.csv")
    - d) df_students= pd.to_df("students.csv")

Assign the character associated with your answer as a string to `ans13`.

In [31]:
### YOUR SOLUTION HERE
ans13= 'a'

###
### YOUR CODE HERE
###


NameError: name 'b' is not defined

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 14
5 points 

For this question, we will use an open source database that collects some health information about patients. Information about the dataset can be found [here](https://www.kaggle.com/burmad/patient#Patient%20Data.csv).

Read the CSV file named `"patients.csv"` in the `data/` folder and assign it to a dataframe called `df_patients`.
Next, extract the columns `gender`, `age`, and `BMI` in the **specified order** and assign them to a new DataFrame called `df_patients_main`.

In [22]:
### YOUR SOLUTION HERE
import pandas as pd
df_patients = pd.read_csv("data/patients.csv")
df_patients_main = pd.DataFrame(df_patients, columns = ['gender', 'age', 'BMI'])
###df_patients.iloc[:, [0,1], [7,8]]###print(df_patients.loc[:, 'gender'], df_patients.iloc[:,5])
###df_patients.iloc[:,'BMI']

df_patients_main
###
### YOUR CODE HERE
###


gender   age    BMI
0      Female  80.0  25.19
1      Female  54.0    NaN
2        Male  28.0    NaN
3      Female  36.0  23.45
4        Male  76.0  20.14
5      Female  20.0    NaN
6      Female  44.0  19.31
7      Female  79.0  23.86
8        Male  42.0  33.64
9      Female  32.0    NaN
10     Female  53.0    NaN
11     Female  54.0  54.70
12     Female  78.0  36.05
13     Female  67.0  25.69
14     Female  76.0    NaN
15       Male  78.0    NaN
16       Male  15.0  30.36
17     Female  42.0  24.48
18     Female  42.0    NaN
19       Male  37.0  25.72
20       Male  40.0  36.38
21       Male   5.0  18.80
22     Female  69.0  21.24
23     Female  72.0  27.94
24     Female   4.0  13.99
25       Male  30.0  33.76
26       Male  67.0    NaN
27       Male  40.0  27.85
28       Male  45.0  26.47
29       Male  43.0  26.08
...       ...   ...    ...
99970    Male  32.0  37.71
99971  Female  57.0  31.78
99972  Female  23.0  21.30
99973  Female  51.0    NaN
99974  Female  51.0  29.16
99975  Female  41.0    NaN
99976    Male  13.0  21.01
99977  Female  22.0  24.46
99978    Male  14.0  23.67
99979  Female  61.0  30.11
99980  Female  52.0    NaN
99981    Male  26.0  24.08
99982  Female  80.0  30.04
99983  Female  21.0    NaN
99984    Male  80.0  20.96
99985    Male  25.0    NaN
99986  Female  63.0  29.01
99987  Female  23.0  17.87
99988    Male  19.0  25.75
99989  Female  26.0    NaN
99990    Male  39.0    NaN
99991    Male  22.0  29.65
99992  Female  26.0  34.34
99993  Female  40.0  40.69
99994  Female  36.0  24.60
99995  Female  80.0    NaN
99996  Female   2.0  17.37
99997    Male  66.0  27.83
99998  Female  24.0  35.42
99999  Female  57.0  22.43

[100000 rows x 3 columns]

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 15
10 points


Take the dataframe `df_patients_main` and create a filter to get all rows where the column `age` is less or equal than 30. Call this new dataframe `df_patients_u30`.

In [26]:
### YOUR SOLUTION HERE
df_patients_u30 = df_patients_main.loc[df_patients_main.age <= 30]
df_patients_u30
###pd.DataFrame(people_np, columns = ['name', 'fav_breakfast', 'age', 'knows_python'])

###
### YOUR CODE HERE
###


gender   age    BMI
2        Male  28.0    NaN
5      Female  20.0    NaN
16       Male  15.0  30.36
21       Male   5.0  18.80
24     Female   4.0  13.99
25       Male  30.0  33.76
33     Female  20.0  22.19
35       Male   5.0  15.10
36     Female  15.0  21.76
37     Female  26.0  21.22
41       Male   5.0    NaN
46     Female  29.0  19.95
49     Female   3.0  19.27
51     Female  26.0    NaN
56       Male  30.0    NaN
57     Female  19.0  23.35
61     Female  21.0  26.10
62     Female  30.0    NaN
64     Female  27.0  30.22
66     Female  19.0    NaN
67     Female  13.0  28.16
69       Male   2.0  23.04
70       Male   7.0  15.94
71       Male   3.0  15.80
72     Female  30.0  27.01
76     Female  11.0  17.98
77     Female  26.0  26.45
89     Female   6.0  16.39
95       Male  19.0    NaN
97       Male  11.0    NaN
...       ...   ...    ...
99917  Female  20.0    NaN
99921  Female  10.0  20.26
99924    Male  16.0  20.14
99927  Female  22.0  25.88
99928    Male  21.0  19.75
99932  Female   7.0  19.77
99933  Female   5.0  13.34
99939    Male  13.0  21.81
99940    Male   2.0  16.86
99949  Female  26.0  21.50
99950    Male  20.0  34.69
99956    Male  26.0  25.60
99959  Female  21.0  22.90
99964    Male  15.0  20.98
99965  Female  30.0    NaN
99969  Female  30.0  22.88
99972  Female  23.0  21.30
99976    Male  13.0  21.01
99977  Female  22.0  24.46
99978    Male  14.0  23.67
99981    Male  26.0  24.08
99983  Female  21.0    NaN
99985    Male  25.0    NaN
99987  Female  23.0  17.87
99988    Male  19.0  25.75
99989  Female  26.0    NaN
99991    Male  22.0  29.65
99992  Female  26.0  34.34
99996  Female   2.0  17.37
99998  Female  24.0  35.42

[33733 rows x 3 columns]

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


[Back to top](#Index:) 

### Question 16
5 points 

Compute the average of the column `BMI` from the DataFrame `df_patients` and assign the value to the variable `average_bmi`.

In [51]:
### YOUR SOLUTION HERE
import numpy as np
average_bmi = np.nanmean(df_patients.BMI)
average_bmi

###
### YOUR CODE HERE


AttributeError: 'list' object has no attribute 'BMI'

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###
